# Generated by Django 4.2.6 on 2023-10-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_ingredients_is_active_products_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
