# Generated by Django 4.2.6 on 2023-10-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_products_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
